### ISSUE TITLE
Tutorials fail to run

### ISSUE THREAD

**Issue by ahagmuller** [WEC-Sim/bemio#15]
Tried to run install_test.py after updating repository to fbdf1023e07c183293439fcf29c34512999d697b
and got the following output:

Testing bemio version 1.1

****Running the tutorials/wamit/COER_hydrodynamic_modeling_comp case****
The tutorials/wamit/COER_hydrodynamic_modeling_comp test case failed
****Running the tutorials/wamit/ecm_ellipsoid case****
The tutorials/wamit/ecm_ellipsoid test case failed
****Running the tutorials/wamit/oswec case****
The tutorials/wamit/oswec test case failed
****Running the tutorials/wamit/rm3 case****
The tutorials/wamit/rm3 test case failed
****Running the tutorials/wamit/sphere case****
The tutorials/wamit/sphere test case failed
****Running the tutorials/wamit/wec3 case****
The tutorials/wamit/wec3 test case failed
****Running the tutorials/nemoh case****
The tutorials/nemoh test case failed
****Running the tutorials/mesh/scale_and_translate case****
The tutorials/mesh/scale_and_translate test case failed
****Running the tutorials/mesh/wamit_to_nemoh case****
The tutorials/mesh/wamit_to_nemoh test case failed
****Running the tutorials/utilities/wave_excitation case****
The tutorials/utilities/wave_excitation test case failed
All test cases run:
	tutorials/wamit/COER_hydrodynamic_modeling_comp: *FAILED*
	tutorials/wamit/ecm_ellipsoid: *FAILED*
	tutorials/wamit/oswec: *FAILED*
	tutorials/wamit/rm3: *FAILED*
	tutorials/wamit/sphere: *FAILED*
	tutorials/wamit/wec3: *FAILED*
	tutorials/nemoh: *FAILED*
	tutorials/mesh/scale_and_translate: *FAILED*
	tutorials/mesh/wamit_to_nemoh: *FAILED*
	tutorials/utilities/wave_excitation: *FAILED*
>>> 

Tried to run individual test case \bemio\tutorials\wamit\rm3\run.py and got the following error:

Traceback (most recent call last):
** IDLE Internal Exception: 
  File "C:\Users\Master\Anaconda\lib\idlelib\run.py", line 324, in runcode
    exec code in self.locals
  File "C:\Users\Master\Documents\GitHub\bemio\tutorials\wamit\rm3\run.py", line 2, in <module>
    from bemio.io.wamit import read
ImportError: cannot import name read
>>>

**Comment by lawsonro3** [comment]
Try changing the import statement to:

'from bemio.io.wamit import WamitOutput'

And change the 'read' command to 'WamitOutput'

Also, be sure that you are using the latest version of the code.

**Comment by ahagmuller** [comment]
Hi,
This error came after downloading the latest release last night. Should the code be changed in the test install file or the individual run.py files for wamit aqwa and Nemoh, or all of the above?
Thanks,
Alex

**Comment by yuyihsiang** [comment]
Hi Alex

Few things in the install_test.py were fixed. It should work for you now. Please download the latest version that I pushed around noon (MT) today. Let us know if it still gives you the same issue.

Thanks,

Yi-Hsiang

Sent from my iPhone

On Aug 5, 2015, at 5:05 PM, ahagmuller <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,
This error came after downloading the latest release last night. Should the code be changed in the test install file or the individual run.py files for wamit aqwa and Nemoh, or all of the above?
Thanks,
Alex




> On Aug 5, 2015, at 11:03 AM, Michael Lawson <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Try changing the import statement to:
>
> 'from bemio.io.wamit import WamitOutput'
>
> And change the 'read' command to 'WamitOutput'
>
> Also, be sure that you are using the latest version of the code.
>
> -
> Reply to this email directly or view it on GitHub.
>

-

**Comment by ahagmuller** [comment]
Hi,
I updated the version and it still has the same problem when I run the
test_install.py that all test cases fail. When I run the individual WAMIT
test cases(RM3, etc.), it first says there is an indentation problem which
I format by untabifying, and then it runs, but I get the following error:


Traceback (most recent call last):
** IDLE Internal Exception:
  File "C:\Users\Master\Anaconda\lib\idlelib\run.py", line 324, in runcode
    exec code in self.locals
  File "C:\Users\Master\Documents\GitHub\bemio\tutorials\wamit\rm3\run.py",
line 2, in <module>
    from bemio.io.wamit import read
ImportError: cannot import name read
>>>


I ran the AQWA and NEMOH individual test cases and get the exact same
error, except they don't come up with an indentation error first.

I also tried changing the import statement in the run.py for the RM3 test
case as Michael suggested and ended up with this error:




Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\bemio\io\output.py", line 1, in <module>
  File "C:\Users\Master\Anaconda\lib\site-packages\h5py\__init__.py", line
13, in <module>
    from . import _errors
ImportError: DLL load failed: %1 is not a valid Win32 application.





Here is the run.py after I modified:

# Load the needed modules from bemio
from bemio.io.wamit import WamitOutput
from bemio.io.output import write_hdf5

# Load plotting functions
#import matplotlib.pyplot as plt
#plt.interactive(True)

# Load the data using the wamit module.
wamit_data = read(out_file='wamit_data/rm3.out',scale=False)


# Calculate IRF and plot using the wamit module
for i in xrange(wamit_data.body[0].num_bodies):
#wamit_data.body[0].num_bodies
wamit_data.body[i].calc_irf_radiation(t_end=20., n_t=1001, n_w=501)
#wamit_data.body[i].calc_ss_radiation()
wamit_data.body[i].calc_irf_excitation(t_end=100., n_t=1001, n_w=501,
w_max=1.25)

# Save the data in the hdf5 format.
write_hdf5(wamit_data)





Thanks!
Alex

**Comment by ahagmuller** [comment]
Also, I am wondering, could this be a Windows compatibility issue?

**Comment by ahagmuller** [comment]
Hi,

Just wanted to update you on this, I installed the latest version of BEMIO
in a virtual machine running Linux and everything worked fine.  I had
problems running openWARP in windows before as well and running in the
virtual machine with Linux seemed to eliminate those issues also.

Anyways, hope this helps.
Thanks,

Alex

**Comment by yuyihsiang** [comment]
Hi Alex

Thanks for testing it. Good to know that at least you find a way to get it around.

Based on the error message, I assume you are using anaconda python. Is that correct? We will take a look into the problem and let you know if we can regenerate the issue and find the solution to it.

Cheers,

Yi-Hsiang Yu, Ph.D.
Research Engineer | Water Power Program
National Renewable Energy Laboratory (NREL)
yi-hsiang.yu@nrel.gov<mailto:Yi-Hsiang.Yu@nrel.gov> | Phone: (303) 3847143

**Comment by ahagmuller** [comment]
Hi,
Yes, I am using Anaconda Python for the windows install I tested.

Alex

**Comment by lawsonro3** [comment]
Hi Alex,

I just tested bemio in a clean version of Anaconda on Windows and it runs completely file. All I did was download the latest version of Anaconda and bemio. I installed Anaconda, that then typed the following commands in the Windows command window:

```shell
cd <location of bemio source directory on your computer>
python setup.py install --user
python install_test.py
```

After running install_test.py I get the following output (note that I reduced the number of cases in the install test in the latest version of python). Please let me know if you are still having problems.

```shell
C:\Users\User\Documents\GitHub\bemio [master]> python .\install_test.py
Running standard test cases:

****Running the tutorials/wamit/COER_hydrodynamic_modeling_comp case****
Reading C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\COER_hydrodynamic_modeling_comp\wamit_data\coer_comp_f.out
        The file C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\COER_hydrodynamic_modeling_comp\wamit_data\coer_comp_f.3sc d
oes not exist... not reading scattering coeffcients.
        The file C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\COER_hydrodynamic_modeling_comp\wamit_data\coer_comp_f.3fk d
oes not exist... not reading froud krylof coeffcients.
Calculating the radiation damping impulse response function for rbWAMIT:100%|#|
Calculating the excitation force impulse response function for rbWAMIT:100%|##|
Writing HDF5 data to coer_comp_f.h5
        Radiation state space coefficients for rbWAMIT were not written.
Reading C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\COER_hydrodynamic_modeling_comp\wamit_data\coer_comp_f.out
        The file C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\COER_hydrodynamic_modeling_comp\wamit_data\coer_comp_f.3sc d
oes not exist... not reading scattering coeffcients.
        The file C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\COER_hydrodynamic_modeling_comp\wamit_data\coer_comp_f.3fk d
oes not exist... not reading froud krylof coeffcients.
        Scaling hydro coefficients by rho, g, and w (e.g. am = am*rho*g)...
Calculating the radiation damping impulse response function for rbWAMIT:100%|#|
Calculating the excitation force impulse response function for rbWAMIT:100%|##|
Writing HDF5 data to coer_comp_f_scaled.h5
        Radiation state space coefficients for rbWAMIT were not written.
****The tutorials/wamit/COER_hydrodynamic_modeling_comp test case ran successfully****

****Running the tutorials/wamit/wec3 case****
Reading C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\wec3\wec3.out
        The file C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\wec3\wec3.3sc does not exist... not reading scattering coeff
cients.
        The file C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\wec3\wec3.3fk does not exist... not reading froud krylof coe
ffcients.
Calculating the radiation damping impulse response function for base:100%|####|
Calculating the excitation force impulse response function for base:100%|#####|
Calculating the radiation damping impulse response function for flap1:100%|###|
Calculating the excitation force impulse response function for flap1:100%|####|
Calculating the radiation damping impulse response function for flap2:100%|###|
Calculating the excitation force impulse response function for flap2:100%|####|
Writing HDF5 data to C:\Users\User\Documents\GitHub\bemio\tutorials\wamit\wec3\wec3.h5
        Radiation state space coefficients for base were not written.
        Radiation state space coefficients for flap1 were not written.
        Radiation state space coefficients for flap2 were not written.
****The tutorials/wamit/wec3 test case ran successfully****

****Running the tutorials/nemoh case****
        Normalizing hydro coefficients by rho, g, and w...
        Spring stiffness not nondimensionalized
        Normalizing hydro coefficients by rho, g, and w...
        Spring stiffness not nondimensionalized
Calculating the radiation damping impulse response function for Cube.dat:100%||
Calculating the excitation force impulse response function for Cube.dat:100%|#|
Calculating the radiation damping impulse response function for Rotated_cube.dat:100%||
Calculating the excitation force impulse response function for Rotated_cube.dat:100%||
Writing HDF5 data to C:\Users\User\Documents\GitHub\bemio\tutorials\nemoh\data\two_body\Nemoh.h5
        Radiation state space coefficients for Cube.dat were not written.
        Radiation state space coefficients for Rotated_cube.dat were not written.
****The tutorials/nemoh test case ran successfully****

****Running the tutorials/aqwa case****
body1:
   * Setting added mass at infinite frequency to added mass at omega = 20.9439526
   * Setting added mass at zero frequency to added mass at omega = 0.7222053
   * Calculating real and imaginary excitation  components.
        Normalizing hydro coefficients by rho, g, and w...
body2:
   * Setting added mass at infinite frequency to added mass at omega = 20.9439526
   * Setting added mass at zero frequency to added mass at omega = 0.7222053
   * Calculating real and imaginary excitation  components.
        Normalizing hydro coefficients by rho, g, and w...
body3:
   * Setting added mass at infinite frequency to added mass at omega = 20.9439526
   * Setting added mass at zero frequency to added mass at omega = 0.7222053
   * Calculating real and imaginary excitation  components.
        Normalizing hydro coefficients by rho, g, and w...
Calculating the radiation damping impulse response function for body1:100%|###|
Calculating the excitation force impulse response function for body1:100%|####|
Calculating the radiation damping impulse response function for body2:100%|###|
Calculating the excitation force impulse response function for body2:100%|####|
Calculating the radiation damping impulse response function for body3:100%|###|
Calculating the excitation force impulse response function for body3:100%|####|
Writing HDF5 data to C:\Users\User\Documents\GitHub\bemio\tutorials\aqwa\data\aqwa_example_data.h5
        Radiation state space coefficients for body1 were not written.
        Radiation state space coefficients for body2 were not written.
        Radiation state space coefficients for body3 were not written.
****The tutorials/aqwa test case ran successfully****

Test cases runs completed:
        tutorials/wamit/COER_hydrodynamic_modeling_comp: SUCCESS
        tutorials/wamit/wec3: SUCCESS
        tutorials/nemoh: SUCCESS
        tutorials/aqwa: SUCCESS
```

**Comment by ahagmuller** [comment]
Okay Mike I will give that a go thanks!
Alex
