### ISSUE TITLE
Single Body NEMOH Error

### ISSUE THREAD

**Issue by ahagmuller** [WEC-Sim/bemio#17]
Hi,
I modified the run.py file to run our single body NEMOH outputs as follows after placing our "ah1" folder in the "data" directory:

#! /usr/bin/python

from bemio.io.nemoh import read

from bemio.io.output import write_hdf5

# ### Read the Nemoh simulation data
nemoh_data = read(sim_dir='./data/ah1', cal_file='Nemoh.cal', results_dir='Results', mesh_dir='Mesh',scale=True)
nemoh_data.read_hydrostatics(body_num=1,file='./data/ah1/Mesh/Hydrostatics.dat')
nemoh_data.read_kh(body_num=1, file='./data/ah1/Mesh/KH_1.dat')

for i in xrange(nemoh_data.body[0].num_bodies):
	nemoh_data.body[i].calc_irf_radiation()
	nemoh_data.body[i].calc_irf_excitation()
	# nemoh_data.body[i].calc_ss_radiation()

write_hdf5(nemoh_data)

When I run our NEMOH files for a single body point absorber this is the error I get:

Warning (from warnings module):
  File "C:\Users\Master\Anaconda\lib\site-packages\PIL\Image.py", line 81
    warnings.warn(str(v), RuntimeWarning)
RuntimeWarning: The _imaging extension was built for another  version of Pillow or PIL

Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\bemio\io\nemoh.py", line 220, in read_hydrostatics
    self.body[body_num].disp_vol = np.float(hydrostatics[3].split()[-1])
KeyError: 1

**Comment by lawsonro3** [comment]
Can you upload a .zip folder of the files you are using when getting this error?

**Comment by lawsonro3** [comment]
Ok, I think I know your problem.

1. Change the body_num to 0 if you only have one body.
  ```
  nemoh_data.read_hydrostatics(body_num=0,file='./data/ah1/Mesh/Hydrostatics.dat') 
  nemoh_data.read_kh(body_num=0, file='./data/ah1/Mesh/KH_1.dat')
  ```

2. I fixed a small oversight in nemoh.py reader. If you update to to the latest version everything should work.

**Comment by ahagmuller** [comment]
HI Mike,
This fixed it and the tutorial singlebody error. I was reading through the
nemoh.py code and it looked like the hydrostatics.read function needs a
file called hydrostatics_1, which is why i changed the name of the NEMOH
file to this even though the single body output for NEMOH just calls the
file hydrostatics.dat. Not sure if this is required.

I have been using WECSim with just body 1 (the upper buoy) of the RM3 wamit
hydro data to get a base configuration for our single body point absorber,
and to confirm function in this way. My plan is to generate a NEMOH output
with the same geometry of the upper buoy for the RM3 device and compare the
results. The way the BEM works with multiple bodies, I am not sure how much
of a difference there would be in the BEM outputs based on their
interactions with each other, but it seemed like a rough place to start.
Also, when trying to model a single body, I can't seem to get the
constraints to work the way I would think, so I have been running no
constraints with the 3 pto's in series with no damping in 2 of the PTO's to
model heave and surge as well. The motion looks like one would expect, but
I am not sure this is how the constraints and PTO's were intended to be
used. I will work through this a bit, could I send you our .slx file at
some point after to compare?
Thanks!

Alex
