### ISSUE TITLE
Error Processing Nemoh results with less than 6 degrees of freedom

### ISSUE THREAD

**Issue by sabible** [WEC-Sim/bemio#19]
Nemoh simulation runs without error with reduced degrees of freedom.  Running bemio is successful when all 6 degrees of freedom, but with reduced freedom I get the following error:
![image](https://cloud.githubusercontent.com/assets/13649571/9209037/7d51f95a-4042-11e5-99de-9938b3d34580.png)

This is likely related to a similar breakdown in the Open-WARP gui.

**Comment by lawsonro3** [comment]
For now, bemio is only working if all the DOFs are simulated. This fix is on the to-do list, but it will most likely not happen for the week or two

**Comment by marcuslehmann** [comment]
We actually found that in your Nemoh.cal file generated by Nemoh using Windows and Anaconda,
you want to delete in
line 9: directory before Name.dat
line 36: ---

**Comment by lawsonro3** [comment]
At this point, I have decided not to update bemio/WEC-Sim to support arbitrary degrees of freedom in NEMOH. I have other priorities at this time and although it is a relatively simple fix, there is significant work to be done to make sure everything is read properly.

That said, if this feature is something that is very important to a significant number of people, I'll spend some time implementing it.

**Comment by kmruehl** [comment]
Alternatively if this is an important feature to the bemio community, you are welcome to make the revision, and submit a pull request: https://help.github.com/articles/using-pull-requests/. We will then make this revision the master version of bemio.
-Kelley
