### ISSUE TITLE
Nemoh Data Import:  Multiple wave angles not importing

### ISSUE THREAD

**Issue by sabible** [WEC-Sim/bemio#20]
After a Nemoh calculation with multiple wave angles and import using Bemio, the HDF5 shows only a single wave at the default angle.  I have checked the Nemoh outputs and they are correctly outputting data for different wave angles.  

![image](https://cloud.githubusercontent.com/assets/13649571/9214557/48bf7b4c-406d-11e5-8d0e-9c03f4c8115c.png)

**Comment by lawsonro3** [comment]
The Nemoh reader is only supporting a single wave direction at this time, but I will push out an update early next week to support multiple wave directions

**Comment by lawsonro3** [comment]
This is now fixed and the bemio Nemoh reader will read Nemoh simulation results with multiple wave directions.

The excitation data is output in the h5 files in 3D arrays. The dimensions of the arrays are [number degrees of freedom, number of wave directions, number of frequencies].

Please let me know if you are having any problems with this functionality.
