### ISSUE TITLE
Error reading NEMOH data

### ISSUE THREAD

**Issue by bjrose86** [WEC-Sim/bemio#22]
I get the following error when using bemio to read my NEMOH data:

![error](https://cloud.githubusercontent.com/assets/13736494/9232452/9356393c-40e2-11e5-9b2f-35716e64fea3.png)

The NEMOH two_body tutorial runs fine, and I checked that the format of all the data files is consistent.

**Comment by bjrose86** [comment]
I get the same error when running the one_body tutorial. The problem appears to be in nemoh.py line 300.

**Comment by ahagmuller** [comment]
Check out Error #21, it has the solution to the problem for a single body,
but you also need to update to the most recent version.
Alex

**Comment by bjrose86** [comment]
Thanks Alex! I changed the body_num=0 and updated to the most recent version of bemio, but I get the same error:

  File "build\bdist.win-amd64\egg\bemio\io\nemoh.py", line 300, in _read_tec
    a[j,0,:] = proc[13].field(1+j*2)

KeyError: 13


Here's the code:

from bemio.io.nemoh import read
from bemio.io.output import write_hdf5
nemoh_data = read(sim_dir='./data/one_body', cal_file='Nemoh.cal', results_dir='Results', mesh_dir='Mesh',scale=True)
nemoh_data.read_hydrostatics(body_num=0,file='./data/one_body/Mesh/Hydrostatics.dat')
nemoh_data.read_kh(body_num=0, file='./data/one_body/Mesh/KH.dat')

for i in xrange(nemoh_data.body[0].num_bodies):
	nemoh_data.body[i].calc_irf_radiation()
	nemoh_data.body[i].calc_irf_excitation()
	# nemoh_data.body[i].calc_ss_radiation()

write_hdf5(nemoh_data)

**Comment by bjrose86** [comment]
Did a clean install and it works now. Thanks again!
