### ISSUE TITLE
Bemio not Importing NEMOH Hydrostatic data

### ISSUE THREAD

**Issue by sabible** [WEC-Sim/bemio#23]
When using the Nemoh/Bemio combination, I have both "Hydrostatics.dat" and "KH.dat" in my "Mesh" folder but bemio does not appear to be reading that information in.  I also tried locating those files in the "Results" folder and the "working directory" but it did not fix the issue.  

![image](https://cloud.githubusercontent.com/assets/13649571/9233676/70f9e314-4102-11e5-8dc1-e6c05a28f330.png)

**Comment by ahagmuller** [comment]
Try changing the name of your Nemoh files to hydrostatics_1.dat and kh_1.dat.

**Comment by sabible** [comment]
Thanks for the suggestion, I played around and found a solution.  If you only have one body then the body is given an index of 0.  Change the read file procedure on your "run.py" file as follows:

nemoh_data.read_hydrostatics(body_num=0,file='./Mesh/Hydrostatics_0.dat')
nemoh_data.read_kh(body_num=0, file='./Mesh/KH_0.dat')

And of course rename the Nemoh output files to match, as suggested by ahagmuller above.
