### ISSUE TITLE
NEMOH Infinite Water Depth For WECSIM

### ISSUE THREAD

**Issue by ahagmuller** [WEC-Sim/bemio#25]
If NEMOH water depth is set to 0 in the nemoh.cal file, which is infinite depth in NEMOH, it is read as actually zero (or seafloor) in WECSIM. I think this is probably because this is how water depth is configured in WAMIT. The fix I have used is to just set the depth in nemoh.cal to a value, say 100m, and run the solver that way.

**Comment by lawsonro3** [comment]
Thanks for finding this error.

I have fixed this issue in the latest version of bemio and if the water depth is specified as 0 in the Nemoh.cal file the HDF5 output file will list the water depth as 'infinite'.

I bemieve this should fix your problem in WEC-Sim, but let me know if you are still having problems

-Mike
