### ISSUE TITLE
WEC-Sim Joint Error

### ISSUE THREAD

**Issue by MattSharman** [WEC-Sim/bemio#27]
Hi All,

This may be a similar issue to #26. But in running WEC-sim with Nemoh I'm getting this error:

>Simulating the WEC device defined in the SimMechanics model Flume_006.slx...   
>Error using wecSim (line 130)
> ['Flume_006/Global Reference Frame/Solver
>Configuration']: Error evaluating equations at time 0.0.
>Stopping simulation.  There may be a singularity in the
>solution.  If not, try reducing the step size (either by
>reducing the fixed step size or by tightening the error
>tolerances)

>Caused by:
    >Error using wecSim (line 130)
    >* ['Flume_006/Floating/Planar Joint']:
   > 'Flume_006/Floating/Planar Joint' has a degenerate mass
   > distribution on its follower side.

Any idea what the problem is? Or where I should start my search?
Many thanks!

**Comment by ahagmuller** [comment]
Is this a single body device?

**Comment by MattSharman** [comment]
Yes

**Comment by ahagmuller** [comment]
Are you using a constraint?

**Comment by ahagmuller** [comment]
If you are running a single body,ale sure you are not running constraints and comment out that section in the input file. Run your PTO block in your power generating dof. 
If you have multiple dof for power generation, run them in series from the global reference frame to the device body. I would first try with a single dof to make sure that gets rid of your degenerate mass issue.

**Comment by lawsonro3** [comment]
Hi Matt, take a look at my post here -https://github.com/WEC-Sim/bemio/issues/26 - and let me know if it solves your problem.

-Mike

**Comment by ahagmuller** [comment]
Hi Mike,
I had this same problem for a single body absorber. I found by removing the
constraint and just running the PTO block(say heave) That this problem went
away. I might have a fundamental misunderstanding of the funciton of the
constraint block however.

For instance, if you run a 6DOF floating constraint and then run a heave
PTO, you would get this error. I ended up running 3 PTO blocks in series
(Heave, Surge, Sway) and setting the damping for the PTO blocks in Surge
and Sway to 0, deleted the constraint block then commented out the
constraint section in the input file. I realized this worked, but am I
missing something big in how the constraints should be used ?
Thanks,
Alex

**Comment by cmichelen** [comment]
Hi,

Can you describe the system you are trying to model?

A 6 DOF constraint connected to a 1 DOF contraint/PTO and then connected to a body would not work. You would need a body/mass between the 6DOF and 1DOF constraints.

If you describe your system I might be able to suggest the best way of modelling it.

**Comment by lawsonro3** [comment]
Hi Matt,

Any update on this issue - I would like to close it if the problem is fixed.

-Mike

**Comment by MattSharman** [comment]
Hi Mike, 

Very sorry for the delay, many projects not enough time. I'm still having this problem. I've been very interested in Alex's findings in issue #26 . I've downloaded his files and run the same wec-sim inputs. I then replicated the same process and ran Bemio using the very same files kindly provided by Alex. However in using my .h5 file this error comes up: 

>Error using wecSim (line 157)
>Derivative of state
>'AH1.Translational_PTO_Local_Z.Translational_PCC_Prismatic_Joint.Pz.v'
>in block 'AH1/Translational PTO  (Local Z)/Translational PCC
>(Prismatic Joint)' at time 6.75 is not finite. The simulation
>will be stopped. There may be a singularity in the solution.  If
>not, try reducing the step size (either by reducing the fixed
>step size or by tightening the error tolerances)

I'm currently comparing the two .h5 files and I'll let you know how I get on.
Could this be a similar 'Swiss Cheesed' hard drive error, or does anyone else know of anything I could try? 

Many Thanks
Matt

**Comment by lawsonro3** [comment]
Hi Matt,

Not sure what the problem could be - if you send me your files I can have a look. Short of that I'm not sure what to tell you.

Sorry I cant be more help,

-Mike

**Comment by kmruehl** [comment]
FYI you can now upload files to Github Issues so that you do not need to email files. This option has the additional benefit of keeping everything in the public domain so that this issue feed can help future bemio users.
-Kelley

**Comment by MattSharman** [comment]
Hi All, 

So managed to try this on a different PC and it seems to be working, I've uploaded the two .h5 files one working and one not Here:

https://www.dropbox.com/sh/fanjcv2ih1f7zy3/AAA-ZmeHmKlbvaVgvomCimm9a?dl=0

Can't find anything myself other than the file size is different. :confounded: 

Thanks for all your help!
Matt
