### ISSUE TITLE
To Scale or Not to Scale

### ISSUE THREAD

**Issue by sabible** [WEC-Sim/bemio#28]
That is the question for both the NEMOH created hydrodynamic stiffness matrix and the response coefficients?  The tutorial Bemio/Nemoh gives a value of "True" in the nemoh_data "read" call in "run.py", but I don't see anything in the Nemoh documentation that indicates the Nemoh output is scaled.

**Comment by lawsonro3** [comment]
WEC-Sim requires that `scale=False`. This is for consistency between WAMIT, AQWA, and NEMOH coefficients.

I'm working on the WEC-Sim and bemio user guides and will include this prominently.

**Comment by sabible** [comment]
Great job mike, thanks for making all this a priority.   We're urgently trying to make it work in support of our wave energy prize work.

Stewart

**Comment by lawsonro3** [comment]
Just to clarify - I believe everything is working if you just specify `scale=False`. The users guide will be updated soon.
