### ISSUE TITLE
Nemoh Calculate IRF

### ISSUE THREAD

**Issue by bradling** [WEC-Sim/bemio#29]
I receive the following error when running bemio to process some Nemoh results:

IOError: [Errno 2] No such file or directory: 'C:\\Users\\Brad\\Documents\\nemoh_run\\results\\IRF.tec'

With this version of Bemio is it necessary to calculate the IRF in Nemoh?
PS - I pulled the latest version of bemio from this site yesterday.

**Comment by lawsonro3** [comment]
Hi Brad,

Sorry for the late response - this appears to be a Nemoh issue. The latest version of Nemoh appears to no longer write out the IRF.tec file, which contains the infinite frequency added mass and impulse response functions for the geometry.

I'll look into fixing this issue this afternoon.

-Mike

**Comment by bradling** [comment]
Mike,

I was able to fix this myself - In the Nemoh.cal file, the calculate IRF must be set to 1 (see image before). Then its the postprocessor.exe that generates the IRF.tec file. So I don't think its a bemio bug that was causing my issue.

Thanks

![image](https://cloud.githubusercontent.com/assets/10558137/9584478/2e73839c-4fc6-11e5-8d13-a5977e64065b.png)

**Comment by lawsonro3** [comment]
Of course... Sorry for the trouble and thanks for figuring out that it just had to be specified in the Nemoh.cal file - I should have known this!

I have added an error check in bemio that reminds users to specify this nemoh option if the IRF.tec is not found. 

Thanks again,

-Mike

**Comment by bradling** [comment]
Thanks for your continued support of this tool Mike!

**Comment by stevenshine** [comment]
@bradling 
Hi
i have same problem with u 
can i  disscuss with u?
 when i use NEMOH caculate hydrodynamic  and then run irregular wave(JONSWAP sptrum)  in wecsim
the wecsim cant run irregular.
Do u know how to modify it? 

Thank u
