### ISSUE TITLE
error reading wamit .out file

### ISSUE THREAD

**Issue by lawsonro3** [WEC-Sim/bemio#3]
If the number of degrees of freedom for each body is not 6, the code will throw an error on the wamit read

**Comment by brauliobarahona** [comment]
Hi Mike, I also ran into that problem. I made this script to read those Wamit files:  

https://github.com/brauliobarahona/readWAMIT.git

The structure is different, but perhaps it is helpful to you.

The class in WecSim (at least the last version I tried) that reads WAMIT, does not handle this. I went to modify it, but it wasn't so trivial. Would that class be used at all in the future or would bemio replace it?

**Comment by lawsonro3** [comment]
Hi Braullio - I'm looking into this now, but won't get a chance to patch the code until tomorrow at the earliest.
