### ISSUE TITLE
Mesh  AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by TadTheno** [WEC-Sim/bemio#33]
We're pretty new to bemio and using it for WECSim.  We are trying to run mesh on STL files to create other formats and keep getting the same error "AttributeError: 'list' object has no attribute 'shape'.  We've tried both STL ASCII and Binary; including not only our own files but the WECSim example STLs as well; always the same error. The error references line 880 in mesh. We're on Windows if that matters. 

Thanks

**Comment by lawsonro3** [comment]
Hi, Can you upload the files that you are having trouble with - if so I ca take a look tomorrow.

Thanks for reporting this error!

-Mike

**Comment by Toby-D** [comment]
Hi Mike, 

Was there any resolution to this issue converting STL meshes? I'm playing with Bemio's meshing abilities and encountered the same error. 

I'm attaching the STL file of a simple sphere that I'm using as a test case.

[Sphere4Bemio.zip](https://github.com/WEC-Sim/bemio/files/217979/Sphere4Bemio.zip)

**Comment by cmichelen** [comment]
This was a bug in the code. It should be resolved now with this commit: https://github.com/WEC-Sim/bemio/commit/0c5b511b60eb21e83b6e3e5e780f290014f02510
