### ISSUE TITLE
Error processing Aqwa simulation with multiple wave headings

### ISSUE THREAD

**Issue by mmacn** [WEC-Sim/bemio#35]
I'm a fairly new bemio user and trying to run bemio on an Aqwa simulation for use in WEC-Sim. Aqwa simulation has several interacting bodies and 8 wave headings. Output *.h5 file created by bemio only lists 6 wave headings, which creates indexing errors in WEC-Sim.

**Comment by lawsonro3** [comment]
Could you send me the AQWA files that give you the error? I have some time
to take a look tomorrow

-Mike

**Comment by cmichelen** [comment]
The latest commit (7 days ago) should have fixed this.
