### ISSUE TITLE
Degree of Freedom

### ISSUE THREAD

**Issue by 10472008** [WEC-Sim/bemio#39]
Hi,
BEMIO is executed success that I set D.O.F=6 in WAMIT.
and when I specify D.O.F=1 in heave motion in WAMIT, BEMIO goes wrong like image below.
Thank you for your helping.
Steve

![bemio_q](https://cloud.githubusercontent.com/assets/23327136/25798284/22876020-3413-11e7-923e-4149bb32cbc9.JPG)

**Comment by kmruehl** [comment]
We are no longer supporting this version of BEMIO. BEMIO is now available within the WEC-Sim functions: https://github.com/WEC-Sim/WEC-Sim/tree/master/source/functions/BEMIO

**Comment by kmruehl** [comment]
@j-vanrij this question is about matlab bemio, but posted on the python bemio site. Can you answer and move to the wec-sim issues page? Thanks.

**Comment by j-vanrij** [comment]
Hi Steve,

As Kelley already noted, we are no longer supporting the python based BEMIO, and it is the MATLAB based BEMIO you have a question on. 

This question has already been answered, in part, in a previous question on the WEC-Sim issues board:
[https://github.com/WEC-Sim/WEC-Sim/issues/169](url)

To reiterate, the MATLAB based BEMIO functions are written assuming the most common scenario, which, in this case, means 6 DOF. Probably the easiest solution would be to just run WAMIT with 6DOF and then only utilize the heave DOF you are interested in.

In reference to your figure, the BEMIO input options are defined:
[http://wec-sim.github.io/WEC-Sim/features.html#bemio](url)

Hope that answers your question. If not, please re-post your question on the WEC-Sim issues page. Thanks.
