### ISSUE TITLE
Single Body Point absorber (buoy)

### ISSUE THREAD

**Issue by haszan21** [WEC-Sim/bemio#40]
I keep getting this error, and I don't know how to fix it, any help!?

Error using wecSim (line 236)
['Buoy/Global Reference Frame/Solver Configuration']: Error evaluating equations at time 0.0.  Stopping simulation.
There may be a singularity in the solution.  If not, try reducing the step size (either by reducing the fixed step
size or by tightening the error tolerances)
Caused by:
    Error using wecSim (line 236)
    ['Buoy/Floating (3DOF)/CONSTRAINT (Planar Joint)']: 'Buoy/Floating (3DOF)/CONSTRAINT (Planar Joint)' has a
    degenerate mass distribution on its follower side.

**Comment by kmruehl** [comment]
It looks like your time-step is too large. have you tried reducing the time-step? 

Also, in the future, please post WEC-Sim questions to the [WEC-Sim issue page](https://github.com/WEC-Sim/WEC-Sim/issues). This is board is for the legacy version of BEMIO.
