### ISSUE TITLE
error in mesh.py _read_stl()

### ISSUE THREAD

**Issue by KevinNJ** [WEC-Sim/bemio#42]
Hi,

Thanks for the excellent piece of software.

In _read_stl(), mesh_data.faces is never made into a numpy array causing any code which requires the 'shape' attribute to crash.

example error:
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    buoy.write(mesh_format='WAMIT')
  File "build\bdist.win-amd64\egg\bemio\mesh_utilities\mesh.py", line 373, in write
  File "build\bdist.win-amd64\egg\bemio\mesh_utilities\mesh.py", line 1011, in _write_gdf
AttributeError: 'list' object has no attribute 'shape'

to fix, the following line of code needs to be inserted at the end of _read_stl()

mesh_data.faces = np.array(mesh_data.faces)

Thanks!

**Comment by kmruehl** [comment]
@KevinNJ thanks for this input. We are actually no longer supporting the Python version of BEMIO. Instead, and have moved bemio over to the [wec-sim source code](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/functions/BEMIO) in MATLAB.
