### ISSUE TITLE
NEMOH EORROR about IRF

### ISSUE THREAD

**Issue by stevenshine** [WEC-Sim/bemio#43]
Hi
When i converter the nemoh to H5 FILE and seem to cant write IRF  and then i cant run irregular wave in wecSim
![image](https://user-images.githubusercontent.com/23226663/33471362-f1b83838-d6a7-11e7-9712-318e12adec78.png)
how to fix it 
thank u

**Comment by kmruehl** [comment]
@stevenshine unfortunately we are no longer supporting the PYTHON version of BEMIO. The BEMIO functionality has been converted to MATLAB is [now included in the WEC-Sim release](https://github.com/WEC-Sim/WEC-Sim/tree/master/source/functions/BEMIO). Please run the MATLAB version of bemio for NEMOH and let us know on the WEC-Sim forum if you still have the same issue. Thank you. 

See [WEC-Sim doc here](http://wec-sim.github.io/WEC-Sim/advanced_features.html#bemio).
