### ISSUE TITLE
plot irf not working

### ISSUE THREAD

**Issue by cmichelen** [WEC-Sim/bemio#6]
Traceback (most recent call last):
  File "S:\WEC-Sim\CM_runs\WEC-Sim_Experiments\v3\hydroData\r
7, in <module>
    aq.data[1].plot_irf(comps_to_plot)
  File "C:\Users\cmichel\Documents\GitHub\bemio\bemio\data_st
ine 389, in plot_irf
    ax[i].set_ylabel('comp ' + str(x) + ',' + str(y))
TypeError: 'AxesSubplot' object does not support indexing

**Comment by brauliobarahona** [comment]
Hi Carlos,


It seems that `components` maybe the issue, are you passing a list with only one item?

Try this:
```
import matplotlib.pyplot as plt
import numpy as np

components = [[0, 0], [1, 1], [2, 2], [3, 3] ]

f, ax = plt.subplots( np.shape(components)[0] )

for i, comp in enumerate(components):
    print i
    print ax[i]
```

You should get a figure with 4 subplots.

Now change `components` to a list with only one element: `components = [ [0, 0] ]` and you will get `TypeError: 'AxesSubplot' object does not support indexing`

Not sure what `components` is, but try making a case for when components has only one item (if that is what is meant), for example:

```
components = [[0, 0]]

f, ax = plt.subplots( np.shape(components)[0] )

for i in range(len(components)):
    print i
    try:
        print ax[i]
    except TypeError:
        print 'there is only one component, so you get one subplot'
        print ax
```

**Comment by lawsonro3** [comment]
Carlos, Is this issue now closed?
